import {
  Pipeline,
  PipelineRun,
  DataQualityCheck,
  DataSource,
  ETLJob,
  DataMetrics,
  QualityBreakdown,
  DataFreshness,
  ErrorBreakdown,
  RunErrorBreakdown,
  SchemaDriftEvent,
  ObservabilityAlert,
  PipelineCostSignal,
  PipelineRecoveryValidation,
} from "./types";

export const dataQualityChecks: DataQualityCheck[] = [
  {
    id: "qc-1",
    pipelineId: "p-1",
    name: "Schema Validation",
    description: "Validates incoming data against expected schema",
    status: "pass",
    score: 99.2,
    threshold: 95,
    lastRun: "2026-06-09T10:30:00Z",
  },
  {
    id: "qc-2",
    pipelineId: "p-1",
    name: "Null Value Detection",
    description: "Monitors for unexpected NULL values in required columns",
    status: "pass",
    score: 97.8,
    threshold: 90,
    lastRun: "2026-06-09T10:30:00Z",
  },
  {
    id: "qc-3",
    pipelineId: "p-2",
    name: "Freshness Check",
    description: "Ensures data is not older than SLA threshold",
    status: "warn",
    score: 88.5,
    threshold: 95,
    lastRun: "2026-06-09T09:45:00Z",
  },
  {
    id: "qc-4",
    pipelineId: "p-2",
    name: "Duplicate Detection",
    description: "Identifies duplicate records in the stream",
    status: "pass",
    score: 96.1,
    threshold: 90,
    lastRun: "2026-06-09T09:45:00Z",
  },
  {
    id: "qc-5",
    pipelineId: "p-3",
    name: "Row Count Anomaly",
    description: "Detects unexpected changes in row volume",
    status: "fail",
    score: 52.3,
    threshold: 90,
    lastRun: "2026-06-09T10:15:00Z",
  },
  {
    id: "qc-6",
    pipelineId: "p-3",
    name: "Value Range Validation",
    description: "Checks numeric fields stay within expected ranges",
    status: "pass",
    score: 94.7,
    threshold: 90,
    lastRun: "2026-06-09T10:15:00Z",
  },
  {
    id: "qc-7",
    pipelineId: "p-4",
    name: "Referential Integrity",
    description: "Verifies foreign key relationships are intact",
    status: "pass",
    score: 98.3,
    threshold: 95,
    lastRun: "2026-06-09T08:00:00Z",
  },
  {
    id: "qc-8",
    pipelineId: "p-5",
    name: "Latency SLA Monitor",
    description: "Tracks end-to-end latency against SLA targets",
    status: "warn",
    score: 85.1,
    threshold: 90,
    lastRun: "2026-06-09T10:45:00Z",
  },
  {
    id: "qc-9",
    pipelineId: "p-6",
    name: "Data Completeness",
    description: "Ensures all expected partitions arrived",
    status: "pass",
    score: 97.0,
    threshold: 95,
    lastRun: "2026-06-09T11:00:00Z",
  },
  {
    id: "qc-10",
    pipelineId: "p-7",
    name: "Outlier Detection",
    description: "Statistical outlier detection on key metrics",
    status: "warn",
    score: 87.4,
    threshold: 90,
    lastRun: "2026-06-09T09:30:00Z",
  },
  {
    id: "qc-11",
    pipelineId: "p-8",
    name: "Schema Drift Detection",
    description: "Detects unexpected schema changes at source",
    status: "pass",
    score: 95.6,
    threshold: 90,
    lastRun: "2026-06-09T10:00:00Z",
  },
  {
    id: "qc-12",
    pipelineId: "p-8",
    name: "Data Type Validation",
    description: "Verifies column data types match expectations",
    status: "pass",
    score: 96.9,
    threshold: 90,
    lastRun: "2026-06-09T10:00:00Z",
  },
];

export const dataFreshnessRecords: DataFreshness[] = [
  {
    id: "freshness-1",
    pipelineId: "p-1",
    expectedMaxAgeMinutes: 60,
    actualAgeMinutes: 28,
    status: "fresh",
    lastChecked: "2026-06-09T10:58:00Z",
    nextCheckDue: "2026-06-09T11:30:00Z",
    businessImpact:
      "Customer 360 dashboard remains within the hourly CRM reporting SLO for sales leadership.",
  },
  {
    id: "freshness-2",
    pipelineId: "p-2",
    expectedMaxAgeMinutes: 5,
    actualAgeMinutes: 3,
    status: "fresh",
    lastChecked: "2026-06-09T10:59:30Z",
    nextCheckDue: "2026-06-09T11:04:30Z",
    businessImpact:
      "Real-time funnel analytics can still support campaign pacing decisions without stale clickstream signals.",
  },
  {
    id: "freshness-3",
    pipelineId: "p-3",
    expectedMaxAgeMinutes: 360,
    actualAgeMinutes: 420,
    status: "stale",
    lastChecked: "2026-06-09T10:20:00Z",
    nextCheckDue: "2026-06-09T10:35:00Z",
    businessImpact:
      "Executive revenue rollups are outside the six-hour SLO while the S3 data lake aggregation failure is investigated.",
  },
  {
    id: "freshness-4",
    pipelineId: "p-4",
    expectedMaxAgeMinutes: 30,
    actualAgeMinutes: 22,
    status: "fresh",
    lastChecked: "2026-06-09T10:55:00Z",
    nextCheckDue: "2026-06-09T11:25:00Z",
    businessImpact:
      "Personalization segments are current enough for profile enrichment and cache refresh decisions.",
  },
  {
    id: "freshness-5",
    pipelineId: "p-5",
    expectedMaxAgeMinutes: 15,
    actualAgeMinutes: 48,
    status: "stale",
    lastChecked: "2026-06-09T10:45:00Z",
    nextCheckDue: "2026-06-09T11:00:00Z",
    businessImpact:
      "CRM webhook lag may cause account teams to miss handoff alerts from high-intent customer events.",
  },
  {
    id: "freshness-6",
    pipelineId: "p-6",
    expectedMaxAgeMinutes: 1440,
    actualAgeMinutes: 90,
    status: "fresh",
    lastChecked: "2026-06-09T10:30:00Z",
    nextCheckDue: "2026-06-10T01:30:00Z",
    businessImpact:
      "The overnight lake load remains fresh enough to feed downstream daily aggregation jobs.",
  },
  {
    id: "freshness-7",
    pipelineId: "p-7",
    expectedMaxAgeMinutes: 5,
    actualAgeMinutes: 17,
    status: "stale",
    lastChecked: "2026-06-09T10:32:00Z",
    nextCheckDue: "2026-06-09T10:37:00Z",
    businessImpact:
      "Paused cache warming is creating stale user-profile lookups for latency-sensitive product surfaces.",
  },
  {
    id: "freshness-8",
    pipelineId: "p-8",
    expectedMaxAgeMinutes: 1440,
    actualAgeMinutes: null,
    status: "unknown",
    lastChecked: "2026-06-09T10:05:00Z",
    nextCheckDue: "2026-06-10T04:30:00Z",
    businessImpact:
      "Archive freshness cannot be confirmed until the MongoDB connector recovers and emits a trusted watermark.",
  },
];

export const schemaDriftEvents: SchemaDriftEvent[] = [
  {
    id: "drift-1",
    pipelineId: "p-6",
    sourceId: "src-1",
    fieldName: "account_tier",
    changeType: "type_changed",
    severity: "breaking",
    status: "remediating",
    detectedAt: "2026-06-09T10:11:00Z",
    downstreamPipelineIds: ["p-3"],
    remediationPlan:
      "Hold Data Lake Aggregator publishing, update the typed revenue transform, and replay the overnight load after the PostgreSQL contract is approved.",
  },
  {
    id: "drift-2",
    pipelineId: "p-5",
    sourceId: "src-7",
    fieldName: "opportunity_stage_confidence",
    changeType: "column_added",
    severity: "warning",
    status: "monitoring",
    detectedAt: "2026-06-09T10:33:00Z",
    downstreamPipelineIds: ["p-8"],
    remediationPlan:
      "Register the nullable CRM field in the MongoDB archive contract before promotion so downstream analysts see an intentional schema extension.",
  },
  {
    id: "drift-3",
    pipelineId: "p-2",
    sourceId: "src-3",
    fieldName: "session_referrer_url",
    changeType: "semantic_change",
    severity: "info",
    status: "resolved",
    detectedAt: "2026-06-09T09:52:00Z",
    downstreamPipelineIds: [],
    remediationPlan:
      "Documented the campaign-tagging semantic shift and confirmed real-time funnel analytics dashboards already normalize the new URL format.",
  },
];


export const observabilityAlerts: ObservabilityAlert[] = [
  {
    id: "alert-1",
    pipelineId: "p-6",
    alertKind: "schema_drift",
    title: "Contract drift threatens overnight lake load",
    severity: "critical",
    businessCriticality: "critical",
    triggeredAt: "2026-06-09T10:12:00Z",
    response: {
      ownerTeam: "Data Platform On-call",
      acknowledgedAt: "2026-06-09T10:14:00Z",
      reviewDueAt: "2026-06-09T10:27:00Z",
      escalationPolicy:
        "Primary data platform owner pages immediately; finance reporting stakeholders receive an incident note if replay is not complete inside the review window.",
    },
    relatedAlertIds: ["alert-2"],
    correlation: {
      rootCauseAlertId: null,
      suppressedDuplicateCount: 14,
      suppressionWindowMinutes: 45,
      clusterReason:
        "Root contract-drift alert absorbs downstream revenue freshness and board-export checks into one incident instead of creating separate pages.",
    },
    downstreamPipelineIds: ["p-3"],
    affectedAssets: [
      {
        name: "Executive revenue rollup dashboard",
        assetType: "dashboard",
        ownerTeam: "Finance Analytics",
        impactSummary:
          "Executive revenue decisions remain on stale aggregates until the replay watermark is verified.",
      },
      {
        name: "Revenue forecast feature store",
        assetType: "feature_store",
        ownerTeam: "ML Platform",
        impactSummary:
          "Forecast features can inherit invalid account tiers while the upstream contract change is unresolved.",
      },
      {
        name: "Board metrics export",
        assetType: "report",
        ownerTeam: "Executive Data Products",
        impactSummary:
          "The next board export must remain blocked rather than publishing revenue metrics from the broken load.",
      },
    ],
    priority: "page_on_call",
    triageRationale:
      "Breaking account_tier drift in the root overnight load maps through lineage to the failed daily aggregate, so one upstream contract fix can suppress the downstream freshness and quality alert noise.",
    recommendedAction:
      "Page the data platform owner, freeze revenue rollup publishing, approve the PostgreSQL contract change, then replay p-6 before p-3 restarts.",
  },
  {
    id: "alert-2",
    pipelineId: "p-3",
    alertKind: "freshness_slo",
    title: "Revenue aggregate breached six-hour freshness SLO",
    severity: "warning",
    businessCriticality: "high",
    triggeredAt: "2026-06-09T10:20:00Z",
    response: {
      ownerTeam: "Analytics Engineering",
      acknowledgedAt: "2026-06-09T10:29:00Z",
      reviewDueAt: "2026-06-09T13:00:00Z",
      escalationPolicy:
        "Analytics engineer owns the finance-facing stale-data banner and escalates to data platform if the root replay misses the same-day review window.",
    },
    relatedAlertIds: ["alert-1"],
    correlation: {
      rootCauseAlertId: "alert-1",
      suppressedDuplicateCount: 0,
      suppressionWindowMinutes: 45,
      clusterReason:
        "Grouped under the upstream contract-drift page so finance freshness symptoms stay visible without paging a second team.",
    },
    downstreamPipelineIds: [],
    affectedAssets: [
      {
        name: "Executive revenue rollup dashboard",
        assetType: "dashboard",
        ownerTeam: "Finance Analytics",
        impactSummary:
          "Finance leaders see a stale-data warning while the six-hour freshness breach remains unresolved.",
      },
      {
        name: "Financial anomaly notebook",
        assetType: "notebook",
        ownerTeam: "Financial Data Science",
        impactSummary:
          "Analysts must defer anomaly conclusions until the aggregate watermark confirms refreshed inputs.",
      },
    ],
    priority: "same_day_review",
    triageRationale:
      "This stale aggregate is grouped with the upstream contract-drift alert instead of paging a second team, keeping analysts focused on the root cause behind the revenue reporting delay.",
    recommendedAction:
      "Keep the stale-data banner visible to finance analysts, then clear the SLO breach only after the overnight load replay refreshes the aggregate watermark.",
  },
  {
    id: "alert-3",
    pipelineId: "p-8",
    alertKind: "connector_health",
    title: "Mongo archive connector has no trusted watermark",
    severity: "warning",
    businessCriticality: "medium",
    triggeredAt: "2026-06-09T10:05:00Z",
    response: {
      ownerTeam: "Data Infrastructure Support",
      acknowledgedAt: null,
      reviewDueAt: "2026-06-09T17:00:00Z",
      escalationPolicy:
        "Support queue watches MongoDB connector recovery and escalates only if archive freshness remains unknown before the daily backfill window.",
    },
    relatedAlertIds: [],
    correlation: {
      rootCauseAlertId: null,
      suppressedDuplicateCount: 0,
      suppressionWindowMinutes: 120,
      clusterReason:
        "Watched separately because no critical live dashboard dependency maps through lineage while the archive connector is offline.",
    },
    downstreamPipelineIds: [],
    affectedAssets: [
      {
        name: "Archive backfill workspace",
        assetType: "workspace",
        ownerTeam: "Data Lifecycle Operations",
        impactSummary:
          "Archive operators cannot schedule a trustworthy backfill until the connector emits a verified watermark.",
      },
    ],
    priority: "watch",
    triageRationale:
      "The archive connector is down, but no critical live dashboard depends on the disabled batch job today, so the alert stays visible without escalating on-call noise.",
    recommendedAction:
      "Open a same-week connector repair ticket, preserve the unknown freshness state, and avoid replaying archive loads until MongoDB emits a trusted watermark.",
  },
];

export const pipelineRecoveryValidations: PipelineRecoveryValidation[] = [
  {
    id: "recovery-1",
    pipelineId: "p-6",
    incidentAlertId: "alert-1",
    replayWindowStart: "2026-06-09T01:00:00Z",
    replayWindowEnd: "2026-06-09T07:30:00Z",
    replayRunId: null,
    rowCountVariancePercent: null,
    qualityChecksPassed: 0,
    qualityChecksRequired: 3,
    downstreamWatermarkVerified: false,
    replayWriteMode: "append",
    deduplicationKey: null,
    idempotencyVerified: false,
    duplicateRowsDetected: null,
    idempotencyEvidence:
      "Append-only replay still lacks an approved business-key deduplication rule, so a retry could duplicate account snapshots in the staging partition.",
    status: "blocked",
    ownerTeam: "Data Platform On-call",
    publishDecisionDueAt: "2026-06-09T12:00:00Z",
    blockingReason:
      "Replay remains blocked until the account_tier contract change is approved and the repaired overnight load can produce a trusted S3 watermark.",
  },
  {
    id: "recovery-2",
    pipelineId: "p-3",
    incidentAlertId: "alert-2",
    replayWindowStart: "2026-06-09T02:00:00Z",
    replayWindowEnd: "2026-06-09T10:16:48Z",
    replayRunId: "run-6",
    rowCountVariancePercent: 0.8,
    qualityChecksPassed: 3,
    qualityChecksRequired: 3,
    downstreamWatermarkVerified: true,
    replayWriteMode: "upsert",
    deduplicationKey: "account_id + revenue_period",
    idempotencyVerified: false,
    duplicateRowsDetected: 27,
    idempotencyEvidence:
      "Dry-run upsert found 27 duplicate account-period keys after replay; merge ordering must be corrected before finance aggregates are republished.",
    status: "validating",
    ownerTeam: "Analytics Engineering",
    publishDecisionDueAt: "2026-06-09T13:00:00Z",
    blockingReason:
      "Replay checks and the downstream watermark are complete, but 27 duplicate business keys keep the finance aggregate in validation.",
  },
  {
    id: "recovery-3",
    pipelineId: "p-2",
    incidentAlertId: null,
    replayWindowStart: "2026-06-09T10:30:00Z",
    replayWindowEnd: "2026-06-09T10:31:12Z",
    replayRunId: "run-4",
    rowCountVariancePercent: 0.2,
    qualityChecksPassed: 3,
    qualityChecksRequired: 3,
    downstreamWatermarkVerified: true,
    replayWriteMode: "partition_overwrite",
    deduplicationKey: "event_id",
    idempotencyVerified: true,
    duplicateRowsDetected: 0,
    idempotencyEvidence:
      "Repeated partition-overwrite verification produced the same event-id set with zero duplicate rows, confirming a safe retry for this window.",
    status: "ready_to_publish",
    ownerTeam: "Streaming Platform",
    publishDecisionDueAt: "2026-06-09T11:15:00Z",
    blockingReason: null,
  },
];

export const pipelineCostSignals: PipelineCostSignal[] = [
  {
    id: "cost-1",
    pipelineId: "p-6",
    windowStart: "2026-06-09T01:00:00Z",
    windowEnd: "2026-06-09T07:30:00Z",
    actualSpendUsd: 1280,
    budgetedSpendUsd: 900,
    variancePercent: 42.2,
    status: "overrun",
    rootCause:
      "The overnight full load retried high-volume PostgreSQL partitions after contract-drift validation failed, stretching warehouse slots beyond the reserved batch window.",
    ownerTeam: "Data Platform FinOps",
    optimizationAction:
      "Pause discretionary backfills, right-size the warehouse class for replay only after schema approval, and move repeat retries behind a cost guardrail before tomorrow's load.",
    nextReviewDueAt: "2026-06-09T12:00:00Z",
  },
  {
    id: "cost-2",
    pipelineId: "p-3",
    windowStart: "2026-06-09T09:00:00Z",
    windowEnd: "2026-06-09T10:30:00Z",
    actualSpendUsd: 760,
    budgetedSpendUsd: 700,
    variancePercent: 8.6,
    status: "watch",
    rootCause:
      "Revenue-aggregate replay planning is adding extra BigQuery scan bytes while the upstream schema repair remains unresolved.",
    ownerTeam: "Analytics Engineering",
    optimizationAction:
      "Keep the finance stale-data banner active, dry-run the replay query plan, and batch non-critical scans until the upstream contract drift is cleared.",
    nextReviewDueAt: "2026-06-09T13:00:00Z",
  },
  {
    id: "cost-3",
    pipelineId: "p-2",
    windowStart: "2026-06-09T10:00:00Z",
    windowEnd: "2026-06-09T11:00:00Z",
    actualSpendUsd: 310,
    budgetedSpendUsd: 350,
    variancePercent: -11.4,
    status: "within_budget",
    rootCause:
      "Kafka consumer lag stayed low enough that autoscaling avoided an unnecessary streaming cluster expansion during campaign pacing checks.",
    ownerTeam: "Streaming Platform",
    optimizationAction:
      "Keep the current autoscaling floor, preserve the five-minute freshness SLO, and review spend only if lag or volume anomalies return.",
    nextReviewDueAt: "2026-06-10T10:00:00Z",
  },
];

export const sourceConnectors: DataSource[] = [
  {
    id: "src-1",
    name: "Production PostgreSQL",
    connectorType: "postgres",
    health: "healthy",
    recordsProcessed: 4820000,
    lastSync: "2026-06-09T10:59:30Z",
    latencyMs: 45,
  },
  {
    id: "src-2",
    name: "Analytics BigQuery",
    connectorType: "bigquery",
    health: "healthy",
    recordsProcessed: 12350000,
    lastSync: "2026-06-09T10:58:12Z",
    latencyMs: 120,
  },
  {
    id: "src-3",
    name: "Clickstream Kafka",
    connectorType: "kafka",
    health: "healthy",
    recordsProcessed: 8900000,
    lastSync: "2026-06-09T10:59:59Z",
    latencyMs: 12,
  },
  {
    id: "src-4",
    name: "Data Lake S3",
    connectorType: "s3",
    health: "degraded",
    recordsProcessed: 6700000,
    lastSync: "2026-06-09T10:45:00Z",
    latencyMs: 340,
  },
  {
    id: "src-5",
    name: "User Profiles MySQL",
    connectorType: "mysql",
    health: "healthy",
    recordsProcessed: 2100000,
    lastSync: "2026-06-09T10:55:00Z",
    latencyMs: 68,
  },
  {
    id: "src-6",
    name: "Cache Redis",
    connectorType: "redis",
    health: "healthy",
    recordsProcessed: 15000000,
    lastSync: "2026-06-09T10:59:45Z",
    latencyMs: 3,
  },
  {
    id: "src-7",
    name: "CRM API Gateway",
    connectorType: "api",
    health: "degraded",
    recordsProcessed: 950000,
    lastSync: "2026-06-09T10:30:00Z",
    latencyMs: 520,
  },
  {
    id: "src-8",
    name: "Events MongoDB",
    connectorType: "mongodb",
    health: "down",
    recordsProcessed: 3400000,
    lastSync: "2026-06-09T08:15:00Z",
    latencyMs: -1,
  },
];

export const pipelineRuns: PipelineRun[] = [
  {
    id: "run-1",
    pipelineId: "p-1",
    status: "success",
    startTime: "2026-06-09T10:00:00Z",
    endTime: "2026-06-09T10:14:32Z",
    recordsIngested: 245000,
    recordsOutput: 244872,
    errors: 128,
    durationMs: 872000,
    throughputRps: 281,
  },
  {
    id: "run-2",
    pipelineId: "p-1",
    status: "success",
    startTime: "2026-06-09T09:00:00Z",
    endTime: "2026-06-09T09:13:45Z",
    recordsIngested: 238000,
    recordsOutput: 237910,
    errors: 90,
    durationMs: 825000,
    throughputRps: 288,
  },
  {
    id: "run-3",
    pipelineId: "p-2",
    status: "running",
    startTime: "2026-06-09T10:55:00Z",
    recordsIngested: 18200,
    recordsOutput: 18150,
    errors: 50,
    durationMs: 300000,
    throughputRps: 60,
  },
  {
    id: "run-4",
    pipelineId: "p-2",
    status: "success",
    startTime: "2026-06-09T10:30:00Z",
    endTime: "2026-06-09T10:31:12Z",
    recordsIngested: 7200,
    recordsOutput: 7185,
    errors: 15,
    durationMs: 72000,
    throughputRps: 100,
  },
  {
    id: "run-5",
    pipelineId: "p-3",
    status: "failed",
    startTime: "2026-06-09T10:15:00Z",
    endTime: "2026-06-09T10:16:48Z",
    recordsIngested: 50000,
    recordsOutput: 45200,
    errors: 4800,
    durationMs: 108000,
    throughputRps: 463,
  },
  {
    id: "run-6",
    pipelineId: "p-3",
    status: "success",
    startTime: "2026-06-09T09:15:00Z",
    endTime: "2026-06-09T09:27:30Z",
    recordsIngested: 520000,
    recordsOutput: 518500,
    errors: 1500,
    durationMs: 750000,
    throughputRps: 693,
  },
  {
    id: "run-7",
    pipelineId: "p-4",
    status: "success",
    startTime: "2026-06-09T08:00:00Z",
    endTime: "2026-06-09T08:45:00Z",
    recordsIngested: 890000,
    recordsOutput: 889200,
    errors: 800,
    durationMs: 2700000,
    throughputRps: 329,
  },
  {
    id: "run-8",
    pipelineId: "p-4",
    status: "queued",
    startTime: "2026-06-09T11:00:00Z",
    recordsIngested: 0,
    recordsOutput: 0,
    errors: 0,
    durationMs: 0,
    throughputRps: 0,
  },
  {
    id: "run-9",
    pipelineId: "p-5",
    status: "success",
    startTime: "2026-06-09T10:45:00Z",
    endTime: "2026-06-09T10:46:30Z",
    recordsIngested: 15000,
    recordsOutput: 14980,
    errors: 20,
    durationMs: 90000,
    throughputRps: 166,
  },
  {
    id: "run-10",
    pipelineId: "p-5",
    status: "running",
    startTime: "2026-06-09T11:00:00Z",
    recordsIngested: 3200,
    recordsOutput: 3195,
    errors: 5,
    durationMs: 50000,
    throughputRps: 64,
  },
  {
    id: "run-11",
    pipelineId: "p-6",
    status: "success",
    startTime: "2026-06-09T06:00:00Z",
    endTime: "2026-06-09T07:30:00Z",
    recordsIngested: 3600000,
    recordsOutput: 3595000,
    errors: 5000,
    durationMs: 5400000,
    throughputRps: 666,
  },
  {
    id: "run-12",
    pipelineId: "p-6",
    status: "cancelled",
    startTime: "2026-06-09T10:00:00Z",
    endTime: "2026-06-09T10:05:00Z",
    recordsIngested: 280000,
    recordsOutput: 140000,
    errors: 0,
    durationMs: 300000,
    throughputRps: 933,
  },
  {
    id: "run-13",
    pipelineId: "p-7",
    status: "success",
    startTime: "2026-06-09T09:30:00Z",
    endTime: "2026-06-09T09:32:00Z",
    recordsIngested: 45000,
    recordsOutput: 44950,
    errors: 50,
    durationMs: 120000,
    throughputRps: 375,
  },
  {
    id: "run-14",
    pipelineId: "p-7",
    status: "failed",
    startTime: "2026-06-09T10:30:00Z",
    endTime: "2026-06-09T10:31:15Z",
    recordsIngested: 12000,
    recordsOutput: 800,
    errors: 11200,
    durationMs: 75000,
    throughputRps: 160,
  },
  {
    id: "run-15",
    pipelineId: "p-8",
    status: "success",
    startTime: "2026-06-09T10:00:00Z",
    endTime: "2026-06-09T10:05:00Z",
    recordsIngested: 180000,
    recordsOutput: 179850,
    errors: 150,
    durationMs: 300000,
    throughputRps: 600,
  },
];


export const runErrorBreakdowns: RunErrorBreakdown[] = [
  {
    runId: "run-1",
    schemaViolations: 12,
    nullViolations: 96,
    timeouts: 0,
    duplicates: 20,
    connectorErrors: 0,
    primaryCategory: "null_violation",
    remediationHint:
      "Review required customer profile fields before the hourly CRM load publishes leadership dashboard snapshots.",
  },
  {
    runId: "run-2",
    schemaViolations: 10,
    nullViolations: 60,
    timeouts: 0,
    duplicates: 20,
    connectorErrors: 0,
    primaryCategory: "null_violation",
    remediationHint:
      "Backfill optional CRM attributes and verify dedupe keys before the next Customer 360 sync window.",
  },
  {
    runId: "run-3",
    schemaViolations: 0,
    nullViolations: 20,
    timeouts: 18,
    duplicates: 0,
    connectorErrors: 12,
    primaryCategory: "null_violation",
    remediationHint:
      "Check streaming watermarks and Kafka consumer lag before campaign pacing data exceeds the five-minute SLA.",
  },
  {
    runId: "run-4",
    schemaViolations: 0,
    nullViolations: 8,
    timeouts: 2,
    duplicates: 5,
    connectorErrors: 0,
    primaryCategory: "null_violation",
    remediationHint:
      "Sample clickstream events for missing campaign IDs and replay duplicate-safe offsets after validation.",
  },
  {
    runId: "run-5",
    schemaViolations: 2800,
    nullViolations: 1200,
    timeouts: 450,
    duplicates: 0,
    connectorErrors: 350,
    primaryCategory: "schema_violation",
    remediationHint:
      "Hold the revenue rollup, diff S3 partition schemas, and escalate upstream contract drift before executive reporting.",
  },
  {
    runId: "run-6",
    schemaViolations: 750,
    nullViolations: 500,
    timeouts: 150,
    duplicates: 100,
    connectorErrors: 0,
    primaryCategory: "schema_violation",
    remediationHint:
      "Audit historical S3 partitions for schema drift and queue a typed transform patch before the next daily aggregate.",
  },
  {
    runId: "run-7",
    schemaViolations: 200,
    nullViolations: 350,
    timeouts: 0,
    duplicates: 250,
    connectorErrors: 0,
    primaryCategory: "null_violation",
    remediationHint:
      "Inspect enrichment join keys and customer ID nullability before personalization segments refresh downstream caches.",
  },
  {
    runId: "run-9",
    schemaViolations: 0,
    nullViolations: 5,
    timeouts: 10,
    duplicates: 0,
    connectorErrors: 5,
    primaryCategory: "timeout",
    remediationHint:
      "Throttle CRM webhook retries and verify API gateway health before account handoff alerts drift further behind.",
  },
  {
    runId: "run-10",
    schemaViolations: 0,
    nullViolations: 2,
    timeouts: 1,
    duplicates: 0,
    connectorErrors: 2,
    primaryCategory: "null_violation",
    remediationHint:
      "Watch the active CRM event stream for connector retries and missing account IDs before replaying pending webhooks.",
  },
  {
    runId: "run-11",
    schemaViolations: 1200,
    nullViolations: 2600,
    timeouts: 600,
    duplicates: 300,
    connectorErrors: 300,
    primaryCategory: "null_violation",
    remediationHint:
      "Validate required PostgreSQL export fields before publishing the overnight lake load to dependent aggregate jobs.",
  },
  {
    runId: "run-13",
    schemaViolations: 0,
    nullViolations: 20,
    timeouts: 0,
    duplicates: 30,
    connectorErrors: 0,
    primaryCategory: "duplicate",
    remediationHint:
      "Quarantine duplicate cache refresh keys and confirm idempotent Redis writes before re-enabling high-frequency warming.",
  },
  {
    runId: "run-14",
    schemaViolations: 5000,
    nullViolations: 1800,
    timeouts: 2200,
    duplicates: 0,
    connectorErrors: 2200,
    primaryCategory: "schema_violation",
    remediationHint:
      "Keep cache warming paused while schema drift and connector retries are resolved to prevent stale profile lookups.",
  },
  {
    runId: "run-15",
    schemaViolations: 40,
    nullViolations: 60,
    timeouts: 20,
    duplicates: 30,
    connectorErrors: 0,
    primaryCategory: "null_violation",
    remediationHint:
      "Verify archive transform defaults before MongoDB event history is promoted into long-term analytics storage.",
  },
];

export const etlJobs: ETLJob[] = [
  {
    id: "job-1",
    pipelineId: "p-1",
    name: "Hourly Customer Sync",
    etlType: "batch",
    sourceId: "src-1",
    destinationId: "src-2",
    schedule: "0 * * * *",
    lastRun: "2026-06-09T10:00:00Z",
    nextRun: "2026-06-09T11:00:00Z",
    avgDurationMs: 845000,
    enabled: true,
  },
  {
    id: "job-2",
    pipelineId: "p-2",
    name: "Real-time Clickstream Ingest",
    etlType: "streaming",
    sourceId: "src-3",
    destinationId: "src-2",
    lastRun: "2026-06-09T10:59:59Z",
    avgDurationMs: 0,
    enabled: true,
  },
  {
    id: "job-3",
    pipelineId: "p-3",
    name: "Daily Batch Aggregation",
    etlType: "batch",
    sourceId: "src-4",
    destinationId: "src-2",
    schedule: "0 2 * * *",
    lastRun: "2026-06-09T02:00:00Z",
    nextRun: "2026-06-10T02:00:00Z",
    avgDurationMs: 4800000,
    enabled: true,
  },
  {
    id: "job-4",
    pipelineId: "p-4",
    name: "User Profile Enrichment",
    etlType: "scheduled",
    sourceId: "src-5",
    destinationId: "src-6",
    schedule: "*/30 * * * *",
    lastRun: "2026-06-09T10:30:00Z",
    nextRun: "2026-06-09T11:00:00Z",
    avgDurationMs: 120000,
    enabled: true,
  },
  {
    id: "job-5",
    pipelineId: "p-5",
    name: "CRM Event Processing",
    etlType: "event-driven",
    sourceId: "src-7",
    destinationId: "src-8",
    lastRun: "2026-06-09T10:45:00Z",
    avgDurationMs: 85000,
    enabled: true,
  },
  {
    id: "job-6",
    pipelineId: "p-6",
    name: "Overnight Full Load",
    etlType: "batch",
    sourceId: "src-1",
    destinationId: "src-4",
    schedule: "0 1 * * *",
    lastRun: "2026-06-09T01:00:00Z",
    nextRun: "2026-06-10T01:00:00Z",
    avgDurationMs: 5400000,
    enabled: true,
  },
  {
    id: "job-7",
    pipelineId: "p-7",
    name: "Redis Cache Refresh",
    etlType: "scheduled",
    sourceId: "src-5",
    destinationId: "src-6",
    schedule: "*/5 * * * *",
    lastRun: "2026-06-09T11:00:00Z",
    nextRun: "2026-06-09T11:05:00Z",
    avgDurationMs: 30000,
    enabled: true,
  },
  {
    id: "job-8",
    pipelineId: "p-8",
    name: "MongoDB to BigQuery ETL",
    etlType: "batch",
    sourceId: "src-8",
    destinationId: "src-2",
    schedule: "0 4 * * *",
    lastRun: "2026-06-09T04:00:00Z",
    nextRun: "2026-06-10T04:00:00Z",
    avgDurationMs: 1800000,
    enabled: false,
  },
];

export const pipelines: Pipeline[] = [
  {
    id: "p-1",
    name: "Customer 360 Sync",
    description: "Hourly ETL pipeline syncing customer data from PostgreSQL to BigQuery for analytics",
    status: "active",
    etlType: "batch",
    sources: [sourceConnectors[0], sourceConnectors[1]],
    upstreamPipelineIds: [],
    qualityChecks: [dataQualityChecks[0], dataQualityChecks[1]],
    jobs: [etlJobs[0]],
    runs: [pipelineRuns[0], pipelineRuns[1]],
    uptimePercent: 99.97,
    avgLatencyMs: 52,
    totalRecordsProcessed: 14823000,
    createdAt: "2026-01-15T08:00:00Z",
    updatedAt: "2026-06-09T10:14:32Z",
  },
  {
    id: "p-2",
    name: "Real-time Clickstream",
    description: "Streaming pipeline ingesting clickstream events from Kafka into BigQuery in near real-time",
    status: "active",
    etlType: "streaming",
    sources: [sourceConnectors[2]],
    upstreamPipelineIds: [],
    qualityChecks: [dataQualityChecks[2], dataQualityChecks[3]],
    jobs: [etlJobs[1]],
    runs: [pipelineRuns[2], pipelineRuns[3]],
    uptimePercent: 99.85,
    avgLatencyMs: 8,
    totalRecordsProcessed: 89200000,
    createdAt: "2026-02-01T10:00:00Z",
    updatedAt: "2026-06-09T10:59:59Z",
  },
  {
    id: "p-3",
    name: "Data Lake Aggregator",
    description: "Daily batch aggregation pipeline processing raw S3 data into summarized BigQuery tables",
    status: "failed",
    etlType: "batch",
    sources: [sourceConnectors[3]],
    upstreamPipelineIds: ["p-6"],
    qualityChecks: [dataQualityChecks[4], dataQualityChecks[5]],
    jobs: [etlJobs[2]],
    runs: [pipelineRuns[4], pipelineRuns[5]],
    uptimePercent: 94.20,
    avgLatencyMs: 210,
    totalRecordsProcessed: 34500000,
    createdAt: "2026-03-10T06:00:00Z",
    updatedAt: "2026-06-09T10:16:48Z",
  },
  {
    id: "p-4",
    name: "User Profile Enrichment",
    description: "Scheduled enrichment pipeline joining MySQL user profiles with behavioral data cached in Redis",
    status: "active",
    etlType: "scheduled",
    sources: [sourceConnectors[4], sourceConnectors[5]],
    upstreamPipelineIds: ["p-1"],
    qualityChecks: [dataQualityChecks[6]],
    jobs: [etlJobs[3]],
    runs: [pipelineRuns[6], pipelineRuns[7]],
    uptimePercent: 99.50,
    avgLatencyMs: 35,
    totalRecordsProcessed: 56100000,
    createdAt: "2026-01-20T12:00:00Z",
    updatedAt: "2026-06-09T11:00:00Z",
  },
  {
    id: "p-5",
    name: "CRM Event Processor",
    description: "Event-driven pipeline consuming CRM webhooks and persisting to MongoDB for operational use",
    status: "active",
    etlType: "event-driven",
    sources: [sourceConnectors[6]],
    upstreamPipelineIds: [],
    qualityChecks: [dataQualityChecks[7]],
    jobs: [etlJobs[4]],
    runs: [pipelineRuns[8], pipelineRuns[9]],
    uptimePercent: 97.80,
    avgLatencyMs: 490,
    totalRecordsProcessed: 8200000,
    createdAt: "2026-04-05T09:00:00Z",
    updatedAt: "2026-06-09T11:00:00Z",
  },
  {
    id: "p-6",
    name: "Overnight Full Load",
    description: "Large-scale batch ETL performing full data load from PostgreSQL to S3 data lake overnight",
    status: "active",
    etlType: "batch",
    sources: [sourceConnectors[0]],
    upstreamPipelineIds: [],
    qualityChecks: [dataQualityChecks[8]],
    jobs: [etlJobs[5]],
    runs: [pipelineRuns[10], pipelineRuns[11]],
    uptimePercent: 99.99,
    avgLatencyMs: 1850,
    totalRecordsProcessed: 287000000,
    createdAt: "2026-01-01T00:00:00Z",
    updatedAt: "2026-06-09T10:05:00Z",
  },
  {
    id: "p-7",
    name: "Cache Warmer",
    description: "High-frequency scheduled pipeline refreshing Redis cache from MySQL user profile data",
    status: "paused",
    etlType: "scheduled",
    sources: [sourceConnectors[4]],
    upstreamPipelineIds: ["p-4"],
    qualityChecks: [dataQualityChecks[9]],
    jobs: [etlJobs[6]],
    runs: [pipelineRuns[12], pipelineRuns[13]],
    uptimePercent: 92.10,
    avgLatencyMs: 18,
    totalRecordsProcessed: 32000000,
    createdAt: "2026-05-01T14:00:00Z",
    updatedAt: "2026-06-09T10:31:15Z",
  },
  {
    id: "p-8",
    name: "MongoDB Archive Pipeline",
    description: "Batch ETL archiving MongoDB event data to BigQuery for long-term analytics storage",
    status: "completed",
    etlType: "batch",
    sources: [sourceConnectors[7]],
    upstreamPipelineIds: ["p-5"],
    qualityChecks: [dataQualityChecks[10], dataQualityChecks[11]],
    jobs: [etlJobs[7]],
    runs: [pipelineRuns[14]],
    uptimePercent: 100,
    avgLatencyMs: 320,
    totalRecordsProcessed: 180000,
    createdAt: "2026-06-01T08:00:00Z",
    updatedAt: "2026-06-09T10:05:00Z",
  },
];

export function computeMetrics(): DataMetrics {
  const activePipelines = pipelines.filter((p) => p.status === "active").length;
  const runsToday = pipelineRuns.filter((r) =>
    r.startTime.startsWith("2026-06-09")
  );
  const totalRunsToday = runsToday.length;
  const failedRunsToday = runsToday.filter((r) => r.status === "failed").length;

  // Error rate: total errors across today's runs as % of total records ingested
  const todayRecords = runsToday.reduce((s, r) => s + r.recordsIngested, 0);
  const todayErrors = runsToday.reduce((s, r) => s + r.errors, 0);
  const errorRatePercent =
    todayRecords > 0
      ? Math.round((todayErrors / todayRecords) * 10000) / 100
      : 0;

  const emptyErrorBreakdown: ErrorBreakdown = {
    schemaViolations: 0,
    nullViolations: 0,
    timeouts: 0,
    duplicates: 0,
    connectorErrors: 0,
  };
  const errorBreakdownByCategory = runErrorBreakdowns.reduce<ErrorBreakdown>(
    (acc, breakdown) => ({
      schemaViolations: acc.schemaViolations + breakdown.schemaViolations,
      nullViolations: acc.nullViolations + breakdown.nullViolations,
      timeouts: acc.timeouts + breakdown.timeouts,
      duplicates: acc.duplicates + breakdown.duplicates,
      connectorErrors: acc.connectorErrors + breakdown.connectorErrors,
    }),
    emptyErrorBreakdown
  );

  const allChecks = pipelines.flatMap((p) => p.qualityChecks);
  const qualityChecksByStatus: QualityBreakdown = {
    pass: allChecks.filter((q) => q.status === "pass").length,
    warn: allChecks.filter((q) => q.status === "warn").length,
    fail: allChecks.filter((q) => q.status === "fail").length,
    pending: allChecks.filter((q) => q.status === "pending").length,
  };

  const qualityScores = pipelines.flatMap((p) =>
    p.qualityChecks.map((qc) => qc.score)
  );
  const overallQualityScore =
    qualityScores.length > 0
      ? Math.round(
          (qualityScores.reduce((a, b) => a + b, 0) / qualityScores.length) * 10
        ) / 10
      : 0;

  const activeThroughput = pipelines
    .filter((p) => p.status === "active" || p.status === "failed")
    .flatMap((p) => p.runs.filter((r) => r.status !== "queued"))
    .reduce((sum, r) => sum + r.throughputRps, 0);

  const uptimes = pipelines.map((p) => p.uptimePercent);
  const avgUptime =
    uptimes.length > 0
      ? Math.round(
          (uptimes.reduce((a, b) => a + b, 0) / uptimes.length) * 100
        ) / 100
      : 0;

  const latencies = pipelines.map((p) => p.avgLatencyMs);
  const avgLatency =
    latencies.length > 0
      ? Math.round(latencies.reduce((a, b) => a + b, 0) / latencies.length)
      : 0;

  return {
    totalPipelines: pipelines.length,
    activePipelines,
    totalRunsToday,
    overallQualityScore,
    totalThroughputRps: activeThroughput,
    failedRunsToday,
    avgLatencyMs: avgLatency,
    uptimePercent: avgUptime,
    qualityChecksByStatus,
    errorRatePercent,
    errorBreakdownByCategory,
  };
}
